services:
  - type: web
    name: bot.py
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false       # set in Render dashboard
      - key: DATABASE_URL
        sync: false       # set in Render dashboard
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: telegram-bot
          property: url