services:
  - type: web
    name: telegram-upload-bot
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: OWNER_ID
        sync: false
      - key: UPLOAD_CHANNEL_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false