services:
  - type: web
    name: telegram-owner-upload-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        fromDatabase: false
      - key: OWNER_ID
        fromDatabase: false
      - key: UPLOAD_CHANNEL_ID
        fromDatabase: false
      - key: DATABASE_URL
        fromDatabase: false
      - key: WEBHOOK_URL
        fromDatabase: false
      - key: PORT
        value: "8080"