services:
  - type: web
    name: telegram-bot
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: UPLOAD_CHANNEL_ID
        sync: false
    healthCheckPath: /health
    ports:
      - 10000