services:
  - type: web
    name: telegram-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_9QTvO4MhbWgB@ep-red-heart-af32eovr-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: WEBHOOK_URL
        sync: false
    healthCheckPath: /health
    region: oregon